//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RulesDef_Dic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictionary
    {
        public int Id { get; set; }
        public string PropAtm { get; set; }
    }
}
